rules:
  - column: user_id
    not_null: true
    unique: true

  - column: age
    type: int
    min: 0
    max: 120
    not_null: true

  - column: email
    regex: '^[^@\s]+@[^@\s]+\.[^@\s]+$'

  - column: signup_date
    type: date
    min: '2020-01-01'
    max: '2025-12-31'
